### ISSUE TITLE
arv-viewer video rendering issue

### ISSUE THREAD

**Issue by PauloFavero** [AravisProject/aravis#522]
Hi guys,

I have installed gstreamer and aravis inside a docker container. The arv-tool works well but when launching the arv-viewer these errors appears:

Gtk-Message: 17:55:29.036: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:55:29.040: Failed to load module "canberra-gtk-module"

```
(arv-viewer-0.8:12): GLib-GIO-CRITICAL **: 17:55:29.397: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
```

I wrote this Dockerfile: 

```
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y build-essential \
    pkg-config \
    python3 \
    python3-pip \
    sudo \
    udev \
    cmake \
    gcc-multilib \
    g++-multilib \
    libcanberra-gtk-module && \
    pip3 install pip --upgrade \
    pip3 install meson \
    pip3 install ninja

WORKDIR /app
COPY aravis-0.8.10.tar.xz ./

RUN tar -xf aravis-0.8.10.tar.xz

ENV DEBIAN_FRONTEND noninteractive

# Install gstreamer
RUN apt-get install -y  libglib2.0-dev libxml2-dev libnotify-dev libaudit-dev libgstreamer* \
    gstreamer1.0-tools \
    gstreamer1.0-alsa \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav

RUN apt-get update && \
    apt-get install -y \
        intltool \
        libgirepository1.0-dev \
        gtk-doc-tools \
        libglib2.0-dev \
        libglibmm-2.4-dev \
        libcanberra-gtk-module

# Build aravis
# https://download-fallback.gnome.org/sources/aravis/0.8/pip
WORKDIR /app/aravis-0.8.10

RUN meson build && cd build && ninja && ninja install
RUN ldconfig

# User configuration
ARG USER_NAME=${USER_NAME}
ARG USER_PASSWORD=${USER_PASSWORD}
ARG USER_UID=${USER_UID}
ARG USER_GID=${USER_UID}

RUN groupadd -g ${USER_GID} ${USER_NAME}

RUN useradd -d /home/${USER_NAME} -s /bin/bash \
    -m ${USER_NAME} -u ${USER_UID} -g ${USER_GID} -G sudo \
    && echo "${USER_NAME}:${USER_PASSWORD}" | \
    chpasswd && adduser ${USER_NAME} sudo && usermod -aG sudo ${USER_NAME} && usermod -a -G video ${USER_NAME}

USER ${USER_NAME}
```

The docker-compose file to build and run this container is the following:

```
version: '3.5'
  
services:
  gstreamer:
    container_name: gstreamer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_NAME=aravis
        - USER_PASSWORD=aravis
        - USER_UID=1000
        - USER_GID=1000
    devices: 
      - "/dev:/dev"
    #   - /dev/ttyACM0:/dev/ttyACM0
    network_mode: "host"
    volumes: 
      - $HOME/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix/:/tmp/.X11-unix
    environment:
      - GST_PLUGIN_PATH=/usr/local/lib/x86_64-linux-gnu/gstreamer-1.0
      - DISPLAY=$DISPLAY
    privileged: true
    command: arv-viewer-0.8
```
Also the interface is not properly rendered when activating a camera. 

![Screenshot from 2021-06-29 15-04-19](https://user-images.githubusercontent.com/26371434/123846097-55016100-d8eb-11eb-9c4d-8fbdb5928c95.png)

Does anyone know what could be the problem?

Thanks,
Paulo
